name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install virtualenv
        virtualenv venv
        source venv/bin/activate
        pip --version
        pip install --trusted-host pypi.python.org -r api_rest/requirements.txt

    - name: Run tests
      run: |
        source venv/bin/activate
        cd api_rest/
        pytest -s -p no:warnings

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v1

    - name: Log in to the GitHub Container Registry
      run: echo ${{ secrets.GHCR_PAT }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build and push Docker image
      run: |
        LATEST_IMAGE=ghcr.io/${{ github.repository }}/agileneva:latest
        docker pull $LATEST_IMAGE || true
        docker build --network host --cache-from $LATEST_IMAGE -t $LATEST_IMAGE .
        docker push $LATEST_IMAGE