version: "3"
services:
  frontend:
    image: ghcr.io/thomasdgr/agilneva/frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"

  backend:
    image: ghcr.io/thomasdgr/agilneva/backend:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - FRONTEND_URL=http://frontend:5173
    depends_on:
      - frontend
