name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Node.js and npm
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install virtualenv
        virtualenv venv
        source venv/bin/activate
        pip --version
        pip install --trusted-host pypi.python.org -r backend/api_rest/requirements.txt

        npm install frontend/api_rest/showcase/agilneva-fe
        cd frontend/api_rest/showcase/agilneva-fe
        ls
        npm run build

    - name: Run tests
      run: |
        source venv/bin/activate
        cd backend/api_rest/
        pytest -s -p no:warnings

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v1

    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Build Frontend 
      run: |
        cd frontend/api_rest/showcase/agilneva-fe
        ls
        npm run build

    - name: Start Docker Compose
      run: |
        ls
        docker-compose down
        docker-compose up -d
        docker-compose build